version: '3.7'

services:
  dev:
    container_name: water_api_dev
    image: water-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    depends_on:
      - db
      - elasticsearch

  elasticsearch:
    container_name: tqd-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1

  # prod:
  #   container_name: water_api_prod
  #   image: water-api-prod:1.0.0
  #   build:
  #     context: .
  #     target: production
  #     dockerfile: ./Dockerfile
  #   depends_on:
  #     - db

  db:
    container_name: water-db
    image: postgres
    restart: always
