version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: water-a-api
    depends_on:
      - db
    env_file:
      - .env
  
  db:
    container_name: water-db
    image: postgres
    restart: always